### ISSUE TITLE
Promotion system

### ISSUE THREAD

**Issue by eisenhowair** [uha-fr/archiweb_2024_projets_gr06#108]
Add a form in the client settings to ask the admin to promote said client to nutritionist by providing necessary informations. The admin can then see from his dashboard the requests, and accept them (or not), thus making the client a nutritionist.

**Comment by eisenhowair** [comment]
don't forget to clear any relation (in the database) to their nutritionist (if they had one ofc) upon the client promoting

**Comment by MathiasBea** [comment]
Noted.
