### ISSUE TITLE
Planning creation

### ISSUE THREAD

**Issue by eisenhowair** [uha-fr/archiweb_2024_projets_gr06#58]
Customer (or a nutritionist having access to his page) can create a planning after entering the duration, the period and a list of recipes.
The recipes they can choose from are from all the database, not just those that user created.

That planning is displayed on the customer page

**Comment by Clstialdev** [comment]
added dataset attributes to the recipe items
added queryparam for the day chosen
added functions to deal with adding the recipe to the JS array

made the meal component dynamic
made the recipes persist using localStorage
made the recipes show as cards

@eisenhowair @khedirwassim

**Comment by khedirwassim** [comment]
Retrieve the recipes array, plan duration, period, and plan name from local storage.
    Use AJAX to send this information to store them in different tables: "plan", "user_plan", and "plan_recipes".
    Implement a function to verify if the user has a plan when the page is opened.
    If the user does not have a plan, display a visible div to insert plan information.
    If the user has a plan, display a div showing plan details (plan name, duration, period), and fetch recipes from the database to     
    place them in the appropriate positions within the plan.

**Comment by khedirwassim** [comment]
Retrieve the recipes array, plan duration, period, and plan name from local storage.
    Utilize AJAX to send this information to store them in different tables: "plan", "user_plan", and "plan_recipes".
    Implement a function to verify if the user has a plan when the page is opened.
    If the user does not have a plan, display a visible div to insert plan information.
    If the user has a plan, display a div showing plan details (plan name, duration, period), 
   and fetch recipes from the database to place them in the appropriate positions within the plan.

**Comment by khedirwassim** [comment]
Retrieve the recipes array, plan duration, period, and plan name from local storage.
use AJAX to send this information to store them in different tables: "plan", "user_plan", and "plan_recipes".
Implement a function to verify if the user has a plan when the page is opened.
If the user does not have a plan, display a visible div to insert plan information.
If the user has a plan, display a div showing plan details (plan name, duration, period), 
   and fetch recipes from the database to place them in the appropriate positions within the plan.
