### ISSUE TITLE
Adding recipes as a nutritionist

### ISSUE THREAD

**Issue by eisenhowair** [uha-fr/archiweb_2024_projets_gr06#93]
Use the form in Views/components/admin/recipesList.php to put its content ( a new recipe ) in the database, thus creating a new recipe.
![image](https://github.com/uha-fr/archiweb_2024_projets_gr06/assets/103502603/b6cc8247-d90f-4382-af36-40f5f5fc53a8)

**Comment by khedirwassim** [comment]
![Capture d’écran 2024-03-17 111420](https://github.com/uha-fr/archiweb_2024_projets_gr06/assets/88117655/2097087c-e4e3-400e-8019-cdf6d714697d)

**Comment by khedirwassim** [comment]
Done
